### ISSUE TITLE
Cannot `go run` because of `replace` directives in the go.mod file

### ISSUE THREAD

**Issue by kolypto** [hedhyw/json-log-viewer#54]
This is what happens when I try to use it as a tool:

```console
$ docker run --rm -it golang
# go run github.com/hedhyw/json-log-viewer/cmd/jlv@latest
go: github.com/hedhyw/json-log-viewer/cmd/jlv@latest (in github.com/hedhyw/json-log-viewer@v0.2.4):
        The go.mod file for the module providing named packages contains one or
        more replace directives. It must not contain directives that would cause
        it to be interpreted differently than if it were the main module.
```

**Comment by hedhyw** [comment]
The reason is because of limitations in `go run` vs `go install`:
https://github.com/golang/go/issues/44840

There're 2 replace directives:
- https://github.com/charmbracelet/bubbles/pull/397
- https://github.com/antonmedv/fx/pull/282

It's possible to run in a different way:
```
git clone https://github.com/hedhyw/json-log-viewer
cd json-log-viewer
go run ./cmd/jlv
```

Reference: https://github.com/hedhyw/json-log-viewer?tab=readme-ov-file#source

**Comment by k3a** [comment]
Why use replace though? Can't you use your forks directly? It is a bit sad that `go run` and `go install` doesn't work :(

**Comment by hedhyw** [comment]
> Why use replace though? Can't you use your forks directly? It is a bit sad that `go run` and `go install` doesn't work :(

I had some hope of switching to the original dependencies. Anyway, I've created an issue: https://github.com/hedhyw/json-log-viewer/issues/159
